export const NavbarLinks=[
    {
        id:1,
        label:'Accueil',
        path:'/'
    },
    {
        id:1,
        label:'producteurs',
        path:'/producteurs'
    },
    {
        id:1,
        label:'projets',
        path:'/projets'
    },
    {
        id:1,
        label:'chatBOT',
        path:'/chatBOT'
    },
    {
        id:1,
        label:'notifications',
        path:'/'
    },
]