import producteur_1 from "../assets/producteur_1.jpg";
export const productors = [
  {
    name: "John's Farm",
    ranking: "4.2",
    products: "Corn,Wheat,Barley",
    id: "12345",
    location: "Bamenda,Northwest",
  },
  {
    name: "Green Valley Farms",
    ranking: "3.8",
    products: "Tomatoes,Cucumbers",
    id: "67890",
    location: "Bafoussam,West",
  },
  {
    name: "Fresh Harvest",
    ranking: "4.5",
    products: "Apples,Oranges,Strawberries",
    id: "54321",
    location: "Ebolowa,South",
  },
  {
    name: "Nature's Bounty",
    ranking: "4.0",
    products: "Carrots,Potatoes",
    id: "09876",
    location: "Limbe,Southwest",
  },
  {
    name: "Sunrise Farms",
    ranking: "4.3",
    products: "Rice,Maize,Soybeans",
    id: "13579",
    location: "Bertoua,East",
  },
  {
    name: "Golden Fields",
    ranking: "3.9",
    products: "Pineapples,Bananas",
    id: "24680",
    location: "Garoua,North",
  },
  {
    name: "Organic Oasis",
    ranking: "4.1",
    products: "Lettuce,Cabbage",
    id: "97531",
    location: "Maroua,Far North",
  },
  {
    name: "Country Fresh",
    ranking: "4.4",
    products: "Grapes,Watermelons",
    id: "86420",
    location: "Buea,Southwest",
  },
  {
    name: "Harvest Moon",
    ranking: "3.7",
    products: "Peppers,Eggplants",
    id: "01928",
    location: "Ngaoundere,Adamawa",
  },
  {
    name: "Farmers' Pride",
    ranking: "4.6",
    products: "Mangoes,Avocados",
    id: "76543",
    location: "Yaounde,Centre",
  },
  {
    name: "Sunset Acres",
    ranking: "4.2",
    products: "Cassava,Yams",
    id: "23456",
    location: "Douala,Littoral",
  },
  {
    name: "Healthy Harvest",
    ranking: "3.8",
    products: "Papayas,Coconuts",
    id: "98765",
    location: "Kumba,Southwest",
  },
  {
    name: "Green Pastures",
    ranking: "4.5",
    products: "Onions,Garlic",
    id: "54321",
    location: "Edea,Littoral",
  },
  {
    name: "Farm to Table",
    ranking: "4.0",
    products: "Pears,Plums",
    id: "09876",
    location: "Bafia,Centre",
  },
  {
    name: "Naturally Fresh",
    ranking: "4.3",
    products: "Cauliflower,Broccoli",
    id: "13579",
    location: "Mbouda,West",
  },
  {
    name: "Golden Harvest",
    ranking: "3.9",
    products: "Sorghum,Millet",
    id: "24680",
    location: "Kribi,South",
  },
  {
    name: "Organic Farmstead",
    ranking: "4.1",
    products: "Spinach,Kale",
    id: "97531",
    location: "Foumban,West",
  },
  {
    name: "Homegrown Delights",
    ranking: "4.4",
    products: "Strawberries,Blueberries",
    id: "86420",
    location: "Mokolo,Far North",
  },
  {
    name: "Field of Greens",
    ranking: "3.7",
    products: "Lettuce,Arugula",
    id: "01928",
    location: "Eseka,Centre",
  },
  {
    name: "Fruitful Harvest",
    ranking: "4.6",
    products: "Grapes,Peaches",
    id: "76543",
    location: "Limbé,Southwest",
  },
  {
    name: "Sunset Farms",
    ranking: "4.2",
    products: "Carrots,Celery",
    id: "23456",
    location: "Bamenda,Northwest",
  },
  {
    name: "Natural Choice",
    ranking: "3.8",
    products: "Tomatoes,Peppers",
    id: "98765",
    location: "Bafoussam,West",
  },
  {
    name: "Fresh Fields",
    ranking: "4.5",
    products: "Apples,Bananas",
    id: "54321",
    location: "Ebolowa,South",
  },
  {
    name: "Farmers' Market",
    ranking: "4.0",
    products: "Potatoes,Corn",
    id: "09876",
    location: "Limbe,Southwest",
  },
  {
    name: "Morning Glory",
    ranking: "4.3",
    products: "Rice,Wheat,Oats",
    id: "13579",
    location: "Bertoua,East",
  },
  {
    name: "Golden Acres",
    ranking: "3.9",
    products: "Pineapples,Mangoes",
    id: "24680",
    location: "Garoua,North",
  },
  {
    name: "Pure Harvest",
    ranking: "4.1",
    products: "Lettuce,Cabbage",
    id: "97531",
    location: "Maroua,Far North",
  },
  {
    name: "Country Freshness",
    ranking: "4.4",
    products: "Grapes,Watermelons",
    id: "86420",
    location: "Buea,Southwest",
  },
  {
    name: "Harvest Delight",
    ranking: "3.7",
    products: "Peppers,Eggplants",
    id: "01928",
    location: "Ngaoundere,Adamawa",
  },
  {
    name: "Farmers' Paradise",
    ranking: "4.6",
    products: "Mangoes,Avocados",
    id: "76543",
    location: "Yaounde,Centre",
  },
  {
    name: "Sunset Fields",
    ranking: "4.2",
    products: "Cassava,Yams",
    id: "23456",
    location: "Douala,Littoral",
  },
  {
    name: "Healthy Farm",
    ranking: "3.8",
    products: "Papayas,Coconuts",
    id: "98765",
    location: "Kumba,Southwest",
  },
  {
    name: "Green Meadows",
    ranking: "4.5",
    products: "Onions,Garlic",
    id: "54321",
    location: "Edea,Littoral",
  },
  {
    name: "Farm Fresh",
    ranking: "4.0",
    products: "Pears,Plums",
    id: "09876",
    location: "Bafia,Centre",
  },
  {
    name: "Naturally Delicious",
    ranking: "4.3",
    products: "Cauliflower,Broccoli",
    id: "13579",
    location: "Mbouda,West",
  },
  {
    name: "Golden Fields",
    ranking: "3.9",
    products: "Sorghum,Millet",
    id: "24680",
    location: "Kribi,South",
  },
  {
    name: "Organic Delights",
    ranking: "4.1",
    products: "Spinach,Kale",
    id: "97531",
    location: "Foumban,West",
  },
  {
    name: "Homegrown Goodness",
    ranking: "4.4",
    products: "Strawberries,Blueberries",
    id: "86420",
    location: "Mokolo,Far North",
  },
  {
    name: "Field to Fork",
    ranking: "3.7",
    products: "Lettuce,Arugula",
    id: "01928",
    location: "Eseka,Centre",
  },
  {
    name: "Fruitful Bounty",
    ranking: "4.6",
    products: "Grapes,Peaches",
    id: "76543",
    location: "Limbé,Southwest",
  },
];
